name: Prepare Release

on:
  release:
    types: [published]

env:
  CGO_ENABLED: 0

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release precompiled binaries
    runs-on: ubuntu-latest
    if: github.event.release.repo == 'parkerduckworth/weaviate'
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@882378b5884e3254db31f1bdbf0f600188f617ae
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.19"
        project_path: "./cmd/weaviate-server"
        extra_files: LICENSE README.md
        ldflags: -w -extldflags "-static" -X github.com/weaviate/weaviate/usecases/config.GitHash='"$GITHASH"'
